name = "my-gtfs-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-03-20"

# Cron trigger: Runs every 4 hours (MYT is UTC+8, so 20:00 UTC)
[triggers]
crons = ["0 */4 * * *"]

# Bind to Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "my-gtfs-db-prod"
database_id = "22a5c5fc-adb6-4b49-aef9-36990ca85189"

[vars]
GTFS_STATIC_URL = "https://api.data.gov.my/gtfs-static/"
# Enum option refer: https://developer.data.gov.my/realtime-api/gtfs-static
GTFS_STATIC_ENUM = """mybas-johor,
ktmb,
prasarana?category=rapid-bus-mrtfeeder,
prasarana?category=rapid-rail-kl,
prasarana?category=rapid-bus-kl,
prasarana?category=rapid-bus-penang"""


[build]
command = "bash ./build.sh"
